on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  validate:
    name: "Validate dataset"
    runs-on: "ubuntu-latest"
    container: ghcr.io/riverbench/dataset-ci-worker:main

    steps:
      - name: "Checkout dataset repository"
        uses: actions/checkout@v3
        with:
          path: dataset
          lfs: true

      - name: "Checkout schema repository"
        uses: actions/checkout@v3
        with:
          repository: 'RiverBench/schema'
          path: schema

      - name: "Validate the dataset"
        run: ci-worker validate-repo dataset schema/src/metadata_shacl.ttl

  package:
    needs: validate
    name: "Package dataset"
    runs-on: "ubuntu-latest"
    container: ghcr.io/riverbench/dataset-ci-worker:main

    steps:
      - name: "Checkout dataset repository"
        uses: actions/checkout@v3
        with:
          path: dataset
          lfs: true
      
      - name: "Package the dataset"
        run: |
          mkdir package_out
          ci-worker package dataset package_out
